spring:
  application:
    name: activity-service
  mongodb:
    uri: mongodb://mongo:password@localhost:27017/fitness-activity?authSource=admin
    database: fitness-activity

server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
